### ISSUE TITLE
hoconDefaults and compilation

### ISSUE THREAD

**Issue by jhalterman** [aalleexxeeii/sbt-hocon#1]
A few questions on hoconDefaults:

* Why does `hoconDefaults` perform compilation on modules? I have a large multi-module project that I was hoping to use sbt-hocon on for creating a merged `reference.conf`, but since `sbt hoconDefaults` performs some compilation it takes too long to run for my use case.
* Is this usage correct: `sbt hoconDefaults merged.conf`? Currently it yields:

```
[error] No valid parser available.
[error] merged.conf
```

**Comment by aalleexxeeii** [comment]
I can recall that the `Compile` phase was the only one where I was able to get full artifacts materialized on the filesystem to feed them to a classloader from which Typesafe Config collected all resources.

When you run an sbt command with arguments from a command line, wrap everything related into double quotes, like `sbt "hoconDefaults merged.conf"`. For multi-module builds, you might want to specify the main module for the task: `moduleName/hoconDefaults`
